# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      addToPath: true
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: pylint git2jss
    displayName: 'Lint'

  - script: |
      python setup.py test -a '--ignore=tests/test_processors.py --deselect=tests/test_vcs.py::test_check_create_tag' 
    displayName: 'Run tests - no JSS'

